/*
 * platform/src/host_visit_maps.c
 *
 * --visit-maps (PLAN.md, Phase 19c): warps to every map in turn and runs
 * some frames on each, to catch crashes in map loading, map scripts and
 * map data that playtesting would take weeks to reach.
 *
 * Each warp is the one upstream's debug menu does (debug.c,
 * DebugSelection_SetWarp_OnComplete): SetWarpDestinationToMapWarp, DoWarp,
 * ResetInitialPlayerAvatarState, ScriptContext_Stop. Unlike the menu, it
 * may warp while a map's script is printing a message, so it first ends
 * the text printers, as a script closes its message before warping: they
 * live on the heap, which the map load resets (MoveSaveBlocks_ResetHeap)
 * before freeing the printers still listed, so one left printing would
 * be freed from the old heap. The player arrives on
 * the map's first warp, or in its middle if it has none
 * (SetPlayerCoordsFromWarp).
 *
 * The run starts from a save: until the game reaches the overworld, A is
 * pressed (title screen, Continue). After that, for each map:
 *   - wait until the overworld can warp (no fade, CB2_Overworld), warp;
 *   - wait until the player is on that map, in the overworld, faded in;
 *   - stay there for DWELL_FRAMES, so its frame scripts, objects and
 *     animations run.
 * Whenever the game is elsewhere for a while (a battle or text a map
 * started), A is pressed now and then to get through it. A map that isn't
 * reached within ARRIVE_FRAMES is reported as stuck.
 *
 * Maps of groups this game doesn't have are skipped: in the Emerald build,
 * FRLG's map groups are NULL in gMapGroups (data/maps/groups.inc). So are
 * the maps in sNeedSetup: reachable only in a state a warp from the
 * overworld doesn't set up (a challenge in progress, ...), whose scripts
 * then go wrong in ways normal play can't reach.
 *
 * Output, one line per map, flushed before the warp so that a crash report
 * follows the map it happened on:
 *   visit-maps: 0.9 MAP_LITTLEROOT_TOWN ... ok
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "global.h"
#include "main.h"
#include "overworld.h"
#include "field_screen_effect.h"
#include "palette.h"
#include "script.h"
#include "text.h"

#include "platform/host_visit_maps.h"
#include "platform/platform.h"

struct MapName
{
    u8 group, num;
    const char *name;
};

/* data/maps/groups.inc */
extern const struct MapHeader *const *const gMapGroups[];

static const struct MapName sMaps[] = {
#include "map_names.inc"
};

static const struct
{
    const char *name;
    const char *reason;
} sNeedSetup[] = {
    /* pyramid_resetparty (on resume) restores the party from
     * frontier.selectedPartyMons, which is 0 outside a challenge: party
     * index -1. */
    { "MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM",
      "needs a Battle Tower multi challenge in progress (Pokemon chosen)" },
    /* The same pyramid_resetparty; the floor's layout is also generated by
     * the challenge. */
    { "MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR",
      "needs a Battle Pyramid challenge in progress (Pokemon chosen, floor generated)" },
};

#define DWELL_FRAMES 60         /* on each map once it's faded in */
#define ARRIVE_FRAMES 1800      /* from the warp to being on the map */
#define START_FRAMES 3600       /* from boot to the overworld */
#define WARP_WAIT_FRAMES 3600   /* for the overworld to be able to warp */
#define MASH_AFTER_FRAMES 120   /* away from the overworld this long: press A */
#define MASH_INTERVAL 16

enum State
{
    STATE_OFF,
    STATE_START,    /* boot to the overworld */
    STATE_WARP,     /* waiting to warp to sMaps[sIndex] */
    STATE_ARRIVE,   /* warped; waiting to be there */
    STATE_DWELL,    /* there; running frames */
    STATE_DONE,
};

static enum State sState = STATE_OFF;
static unsigned sFirstGroup, sLastGroup;
static size_t sIndex;
static uint32_t sSince;         /* frame the current state began */
static uint32_t sAwaySince;     /* frame the game left the overworld, or 0 */
static unsigned sVisited, sStuck, sSkipped, sNeedSetupSkipped;
static bool sFailed;

bool HostVisitMaps_Parse(const char *groups)
{
    unsigned first, last;
    char extra;

    if (strcmp(groups, "all") == 0)
    {
        first = 0;
        last = 255;
    }
    else if (sscanf(groups, "%u-%u%c", &first, &last, &extra) == 2)
    {
    }
    else if (sscanf(groups, "%u%c", &first, &extra) == 1)
    {
        last = first;
    }
    else
    {
        return false;
    }
    if (first > last || first > 255)
        return false;
    sFirstGroup = first;
    sLastGroup = last;
    sState = STATE_START;
    return true;
}

static bool InOverworld(void)
{
    return gMain.callback2 == CB2_Overworld && !gPaletteFade.active;
}

static bool OnMap(const struct MapName *map)
{
    return gSaveBlock1Ptr->location.mapGroup == map->group
        && gSaveBlock1Ptr->location.mapNum == map->num;
}

/* A map on the sNeedSetup list: reported and skipped. */
static bool NeedsSetup(const struct MapName *map)
{
    size_t i;

    for (i = 0; i < ARRAY_COUNT(sNeedSetup); i++)
    {
        if (strcmp(map->name, sNeedSetup[i].name) == 0)
        {
            printf("visit-maps: %u.%u %s ... skipped: %s\n", map->group, map->num, map->name,
                   sNeedSetup[i].reason);
            fflush(stdout);
            sNeedSetupSkipped++;
            return true;
        }
    }
    return false;
}

/* The next map to visit, from sIndex on; false at the end. */
static bool FindMap(void)
{
    for (; sIndex < ARRAY_COUNT(sMaps); sIndex++)
    {
        const struct MapName *map = &sMaps[sIndex];

        if (map->group < sFirstGroup || map->group > sLastGroup)
            continue;
        if (gMapGroups[map->group] == NULL)
        {
            sSkipped++;
            continue;
        }
        if (NeedsSetup(map))
            continue;
        return true;
    }
    return false;
}

static void Finish(void)
{
    printf("visit-maps: %u maps visited, %u stuck, %u skipped (need setup), %u skipped (not in"
           " this game)\n", sVisited, sStuck, sNeedSetupSkipped, sSkipped);
    fflush(stdout);
    if (sStuck != 0)
        sFailed = true;
    sState = STATE_DONE;
    Platform_RequestQuit();
}

static void Fail(const char *why)
{
    printf("visit-maps: %s\n", why);
    sFailed = true;
    Finish();
}

static void Enter(enum State state, uint32_t frame)
{
    sState = state;
    sSince = frame;
}

/* The next map, or the end. */
static void NextMap(uint32_t frame)
{
    sIndex++;
    if (FindMap())
        Enter(STATE_WARP, frame);
    else
        Finish();
}

/* As upstream's debug menu warps (DebugSelection_SetWarp_OnComplete), after
 * ending any message still printing (see the top of the file). */
static void Warp(const struct MapName *map)
{
    printf("visit-maps: %u.%u %s ...", map->group, map->num, map->name);
    fflush(stdout);
    DeactivateAllTextPrinters();
    SetWarpDestinationToMapWarp(map->group, map->num, 0);
    DoWarp();
    ResetInitialPlayerAvatarState();
    ScriptContext_Stop();
}

/* A, now and then, while the game has been away from the overworld for a
 * while: through the title screen, battles, text. */
static uint16_t Mash(uint32_t frame)
{
    if (InOverworld())
    {
        sAwaySince = 0;
        return 0;
    }
    if (sAwaySince == 0)
        sAwaySince = frame;
    if (frame - sAwaySince >= MASH_AFTER_FRAMES && frame % MASH_INTERVAL == 0)
        return PLATFORM_BUTTON_A;
    return 0;
}

uint16_t HostVisitMaps_Frame(uint32_t frame)
{
    const struct MapName *map = &sMaps[sIndex];

    switch (sState)
    {
    case STATE_OFF:
    case STATE_DONE:
        return 0;

    case STATE_START:
        if (sSince == 0)
            sSince = frame;
        if (gMain.callback2 == CB2_Overworld)
        {
            if (!FindMap())
            {
                if (sSkipped + sNeedSetupSkipped == 0)
                    Fail("no maps in those groups");
                else
                    Finish();
                return 0;
            }
            Enter(STATE_WARP, frame);
            return 0;
        }
        if (frame - sSince > START_FRAMES)
        {
            Fail("never reached the overworld (start from a save: -s DIR)");
            return 0;
        }
        /* Every 30 frames: the title screen, then Continue. */
        return frame % 30 == 0 ? PLATFORM_BUTTON_A : 0;

    case STATE_WARP:
        if (InOverworld())
        {
            Warp(map);
            Enter(STATE_ARRIVE, frame);
            return 0;
        }
        if (frame - sSince > WARP_WAIT_FRAMES)
        {
            Fail("the game never got back to the overworld to warp");
            return 0;
        }
        return Mash(frame);

    case STATE_ARRIVE:
        if (OnMap(map) && InOverworld())
        {
            Enter(STATE_DWELL, frame);
            return 0;
        }
        if (frame - sSince > ARRIVE_FRAMES)
        {
            printf(" stuck (on %u.%u, %s)\n", gSaveBlock1Ptr->location.mapGroup,
                   gSaveBlock1Ptr->location.mapNum,
                   gMain.callback2 == CB2_Overworld ? "overworld" : "not in the overworld");
            fflush(stdout);
            sStuck++;
            NextMap(frame);
            return 0;
        }
        return Mash(frame);

    case STATE_DWELL:
        if (frame - sSince >= DWELL_FRAMES)
        {
            printf(" ok\n");
            fflush(stdout);
            sVisited++;
            NextMap(frame);
            return 0;
        }
        return Mash(frame);
    }
    return 0;
}

int HostVisitMaps_ExitStatus(void)
{
    return sFailed ? 1 : 0;
}
