"""Generate the map list for --visit-maps (host_visit_maps.c): one
{group, num, "MAP_NAME"} entry per map, in group and map order, from
upstream's generated include/constants/map_groups.h."""
import pathlib
import re
import sys

header, output = map(pathlib.Path, sys.argv[1:])

maps = []
for line in header.read_text(encoding='utf-8').splitlines():
    match = re.match(r'^\s*(MAP_\w+)\s*=\s*\((\d+)\s*\|\s*\((\d+)\s*<<\s*8\)\)', line)
    if match:
        name, num, group = match.group(1), int(match.group(2)), int(match.group(3))
        maps.append((group, num, name))
if not maps:
    sys.exit(f'{header}: no maps found')
maps.sort()

output.write_text(
    '/* Generated by platform/tools/map_names.py from constants/map_groups.h. */\n'
    + ''.join(f'{{{group}, {num}, "{name}"}},\n' for group, num, name in maps),
    encoding='utf-8')
